version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    volumes:
      - ${PWD}/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ${PWD}/pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - my-network

  data-processor:
    build: ./code
    container_name: data-processor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ny_taxi
      TABLE: green_tripdata_2019
      FILENAME: green_tripdata_2019-01
    networks:
      - my-network
    depends_on:
      - postgres
networks:
  my-network:
    driver: bridge